modLoader="javafml"
loaderVersion="[35,)"

license="GPL-3.0-only"
issueTrackerURL="https://github.com/cqszott01/factorio-mc/issues"

[[mods]]
modId="fmcb"

# The version number of the mod - there's a few well known ${} variables useable here or just hardcode it
# ${file.jarVersion} will substitute the value of the Implementation-Version as read from the mod's JAR file metadata
# see the associated build.gradle script for how to populate this completely automatically during a build
version="0.0.1" #mandatory
displayName="FMCB"
# A URL to query for updates for this mod. See the JSON update specification <here>
updateJSONURL="http://myurl.me/" #optional
displayURL="https://github.com/cqszott01/factorio-mc"
# A file name (in the root of the mod JAR) containing a logo for display
logoFile="examplemod.png" #optional
authors="MegaGlub & the4naves"
description='''
Contains the FMCB Minecraft subsystem.
'''